import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} flex justify-center bg-[#E9E9E9] antialiased`}>
        <div
          className={
            "h-lvh w-full max-w-lg bg-white shadow-[10px_0px_20px_rgba(0,0,0,0.1),-10px_0px_20px_rgba(0,0,0,0.1)]"
          }
        >
          {children}
        </div>
      </body>
    </html>
  );
}
